openapi: 3.0.3
info:
  title: SpeedTestApi
  version: 1.0.0

paths:
  /texts:
    get:
      summary: Получить текст
      tags:
        - Texts
      parameters:
        - name: language
          in: query
          schema:
            $ref: '#/components/schemas/TextLanguage'
          required: true
        - name: lengthType
          in: query
          schema:
            $ref: '#/components/schemas/TextLengthType'
          required: true
      responses:
        '200':
          description: Текста для теста скорости печати
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Text'
        '404':
          description: Ошибка получения текста
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Нет такого текста
              
components:
  schemas:
    Text:
      type: object
      properties:
        id:
          type: string
          example: 123
        content:
          type: string
          example: 'Some text example'
        language:
          $ref: '#/components/schemas/TextLanguage'
        lengthType: 
          $ref: '#/components/schemas/TextLengthType'
      
    TextLanguage:
      type: string
      enum: [ru, en]
      
    TextLengthType:
      type: string
      enum: [short, medium, long]